# Generated by Django 5.0.4 on 2024-04-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Email')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcionProducto', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='aplicacionweb.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('emailAdministrador', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Email')),
                ('nombreAdministrador', models.CharField(max_length=50, verbose_name='Nombre')),
                ('contraseñaAdministrador', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('avatarAdministrador', models.ImageField(blank=True, null=True, upload_to='administradores')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='aplicacionweb.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigoPostal', models.CharField(max_length=10, verbose_name='Codigo Postal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='aplicacionweb.usuario')),
            ],
        ),
    ]
