# Generated by Django 5.0.4 on 2024-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb', '0003_alter_usuario_contrasena_alter_usuario_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuario'),
        ),
    ]
