# Generated by Django 5.0.4 on 2024-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb', '0005_categoria_proveedor_pedido_producto_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjero', 'Extranjero')], default='Nacional', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Familiar', 'Familiar'), ('Cooperativo', 'Cooperativo'), ('Eurogame', 'Eurogame'), ('Deckbuilding', 'Deckbuilding'), ('Solitario', 'Solitario')], max_length=50),
        ),
    ]
